Изможеров Илья. Stack V1.0
TrueCraftWorld/prosoft-c-stack pull request #1
Opened 2023-11-27 07:03 UTC by TrueCraftWorld

Рабочий(если верить тестам) вариант библиотеки стеков.

2023-12-03 11:34 UTC, czertyaka requested changes
В целом хорошее решение, но есть замечания

2023-12-03 11:34 UTC, czertyaka commented on .vscode/settings.json
Обычно такие вещи в git не добавляют) Но тут ваш репозиторий, настаивать не буду

2023-12-03 11:34 UTC, czertyaka commented on cstack.c
> +    uint64_t size;                  // user data size in bytes
Для переменных/полей, которые содержат колчество чего -то (например, это поле `size`) лучше использовать тип `size_t`. Использование этого типа автоматически гарантирует вам, что переменной хватит для исчисления любых объектов в оперативной памяти.

2023-12-03 11:34 UTC, czertyaka commented on cstack.c
> +@brief - function to get stack pointe
Лайк за использование doxygen, но кажется тире после секций `@brief`/`@param`/etc [не нужны](https://www.doxygen.nl/manual/docblocks.html).

2023-12-03 11:34 UTC, czertyaka commented on cstack.c
> +@retval - stackListElem * pointer to ctack container, returns NUL if no such stack
Я думаю тут правильнее использовать `@return`, [пруф](https://sourceforge.net/p/doxygen/mailman/message/11651182/).

2023-12-03 11:34 UTC, czertyaka commented on cstack.c
> +    if (data_out == NULL) return 0;
Строка дублируется

2023-12-03 11:34 UTC, czertyaka commented on cstack.c
> +                if (tmp->nextElem) tmp->nextElem = tmp->nextElem->nextElem;
Тут как-то нелогично:
1. сначала обращаемся к `tmp->nextElem->id`
2. и уже потом проверяем, что `tmp->nextElem->id` не `NULL`

2023-12-03 11:34 UTC, czertyaka commented on cstack.c
> +    memcpy(data_out, tmp->thisStack->top->data,  tmp->thisStack->top->size); //return stored dta
В C11 появилась более безопасная версия memcpy: [memcpy_s](https://en.cppreference.com/w/c/string/byte/memcpy).

2023-12-03 11:34 UTC, czertyaka commented on cstack.c
> +stackListElem *getStackP (const hstack_t hstack) {
Внутренним функциям библиотеки, предназначенным для использования только из этой единицы трансляции, советую обеспечить [internal linkage](https://en.cppreference.com/w/c/language/storage_duration). Тогда у пользователя не будет проблем, если он захочет определить собственную функцию `getStackP`.

Пример без internal linkage:
```
$ cat main.c 
int main() {}

void foo() {}

$ cat foo.c 
int foo() {}

$ cc main.c foo.c
/usr/bin/ld: /tmp/ccrXtvnH.o: in function `foo':
foo.c:(.text+0x0): multiple definition of `foo'; /tmp/ccSdwxT5.o:main.c:(.text+0xb): first defined here
collect2: error: ld returned 1 exit status
```
Пример с internal linkage:
```
$ cat foo.c 
static int foo() {}

$ cc main.c foo.c
```

2023-12-03 11:34 UTC, czertyaka commented on cstack.c
> +        (tmp->thisStack->top->size != size)) return res; //in case of incorrect params - quit before we mess up memory
Тут можно более мягкое условие сделать. Что если в верхушке стека лежит 1 байт, а пользователь предоставил буфер под 2? Вроде никаких проблем: копируем 1 байт и возвращаем единицу.

2023-12-03 11:34 UTC, czertyaka commented on cstack.c
> +            if (doomed->thisStack->top->prevElem)
Нет гарантий, что `top` - не `NULL`

2023-12-03 16:46 UTC, TrueCraftWorld commented on .vscode/settings.json
Тут, к сожалению, мало знаком с коммитами внутри гитхаба - на работе локальная Mercurial. Посмотрю как игнор настроить

2023-12-03 17:45 UTC, TrueCraftWorld commented on cstack.c
> +    memcpy(data_out, tmp->thisStack->top->data,  tmp->thisStack->top->size); //return stored dta
Пишут, что не все версии стандартной библиотеки С поддерживают *_s() функции. В glibc такого нет. [пруф1](https://stackoverflow.com/questions/31278172/undefined-reference-to-memcpy-s), [пруф2](https://www.reddit.com/r/learnprogramming/comments/5uq1sl/c_language_replace_memcpy_with_memcpy_s_i_cant/?rdt=54980)
В бесплатном драфте стандарта сказано, что функции из Annex K опциональны, соответственно применение таковых бьёт по портабельности.
![image](https://github.com/TrueCraftWorld/prosoft-c-stack/assets/123190195/d1523f2c-47c4-4bc6-8941-cd392c9aa796)

2023-12-03 17:51 UTC, TrueCraftWorld commented on cstack.c
> +        (tmp->thisStack->top->size != size)) return res; //in case of incorrect params - quit before we mess up memory
Исправил

2023-12-03 17:51 UTC, TrueCraftWorld commented on cstack.c
> +            if (doomed->thisStack->top->prevElem)
исправил

2023-12-03 17:52 UTC, TrueCraftWorld commented on cstack.c
> +stackListElem *getStackP (const hstack_t hstack) {
Исправил

2023-12-03 17:52 UTC, TrueCraftWorld commented on cstack.c
> +                if (tmp->nextElem) tmp->nextElem = tmp->nextElem->nextElem;
Исправил

2023-12-03 17:52 UTC, TrueCraftWorld commented on cstack.c
> +    if (data_out == NULL) return 0;
Исправил

2023-12-03 17:58 UTC, TrueCraftWorld commented on cstack.c
> +    uint64_t size;                  // user data size in bytes
Исправил

2023-12-03 17:58 UTC, TrueCraftWorld commented on cstack.c
> +@brief - function to get stack pointe
Отредактировал

2023-12-06 18:05 UTC, czertyaka requested changes

2023-12-06 18:05 UTC, czertyaka commented on cstack.c
> +                if (doomed->thisStack->top->prevElem)
Допустим, в прошлой итерации мы присвоили `doomed->thisStack->top` значение `tmpElem`, которое выше было проинициализировано `NULL`. В этом случае обращение к `prevElem` будет нести опасность разыменования нулевого указателя

2023-12-06 18:13 UTC, TrueCraftWorld commented on cstack.c
> +                if (doomed->thisStack->top->prevElem)
присвоить `doomed->thisStack->top` `NULL` мы ведь можем только если `doomed->thisStack->top`  единственным элементом в стеке, тогда итерации где мы это сделали будет последней. Или всё же необходимо явно от этого защититься?

2023-12-06 18:24 UTC, czertyaka commented on cstack.c
> +                if (doomed->thisStack->top->prevElem)
Кажется, понял вас, при наличии других элементов в первой итерации всегда будет истинно условие `if (doomed->thisStack->top->prevElem)` и в `tmpElem` нулевое значение перетрется `doomed->thisStack->top->prevElem`.

В принципе, такое решение безопасно, и я его принимаю)
Но на всякий случай хотел бы отметить, что гарантии безопасности на уровне инвариантов программы (в вашем случае инвариантом будет то, что при наличии нулевого `thisStack->top->prevElem` всегда равен `thisStack->stackSize`) очень легко нарушить, если работать над проектом долго и не в одиночку. Обычно проверки стараются все-таки писать, скажем так, на будущее) Вдруг кто-то придет, и изменит инвариант программы. Но для учебного проекта не обязательно.

2023-12-06 18:24 UTC, czertyaka approved these changes
Задание принято)

2023-12-06 18:35 UTC, czertyaka commented on .vscode/settings.json
Файл .gitignore

2023-12-07 04:56 UTC, TrueCraftWorld commented on cstack.c
> +                if (doomed->thisStack->top->prevElem)
С этим согласен - в проекте вообще достаточно таких мест, где изменение условно-приватной части может нарушить логику проверок. Понятн, что для "рабочего" проекта проверки надо писать более устойчивые к внутренним изменениям.

2023-12-07 05:11 UTC, merged